# Generated by Django 4.1.3 on 2022-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=600)),
                ('current_price', models.IntegerField()),
                ('photo', models.URLField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
