# Generated by Django 4.1.3 on 2022-12-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
