# Generated by Django 4.1.3 on 2022-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionlisting_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
